[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variables for production
# Note: Add your Google Analytics Measurement ID in Netlify dashboard
# Site settings → Environment variables → NEXT_PUBLIC_GA_MEASUREMENT_ID
[build.environment]
  # NEXT_PUBLIC_GA_MEASUREMENT_ID will be set via Netlify UI
