[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/contact"
  to = "/.netlify/functions/__nf_ssr"
  status = 200
  force = true

[functions]
  included_files = ["**"]
