backend:
  name: git-gateway
  branch: main

media_folder: public/images/projects
public_folder: /images/projects

collections:
  - name: "projects"
    label: "Projets"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description courte", name: "description", widget: "string" }
      - { label: "Catégorie", name: "category", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Image principale", name: "image", widget: "image", required: false }
      - { label: "Description complète", name: "fullDescription", widget: "text" }
      - label: "Fonctionnalités"
        name: "features"
        widget: "list"
        field: { label: "Fonctionnalité", name: "feature", widget: "string" }
      - label: "Technologies"
        name: "technologies"
        widget: "list"
        field: { label: "Technologie", name: "technology", widget: "string" }
      - label: "Galerie d'images"
        name: "gallery"
        widget: "list"
        required: false
        field: { label: "Image", name: "image", widget: "image" }
